version: '3'
services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: helix.providersearch
    environment:
      DEBUG_METRICS: 0
      FLASK_ENV: development
    ports:
      - '5000:5000'
    volumes:
    - ./providersearch:/usr/src/helix.providersearch/providersearch/:delegated
    - ./tests:/usr/src/helix.providersearch/tests/:cached
    healthcheck:
      test: curl --fail -s http://localhost:5000/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
