version: '3'
services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: {{cookiecutter.docker_image_name}}
    environment:
      DEBUG_METRICS: 0
      DD_TRACE_ENABLED: "false"
      LOG_LEVEL: INFO
    env_file: docker.env
    ports:
      - '5050:5000'
    volumes:
    - ./:/usr/src/{{cookiecutter.directory_name}}/
    command: ["uvicorn", "{{cookiecutter.project_slug}}.api:app", "--host", "0.0.0.0", "--port", "5000", "--reload", "--log-level", "debug"]
    healthcheck:
      test: curl --fail -s http://localhost:5000/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
