version: '3'
services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: {{cookiecutter.docker_image_name}}
    environment:
      DEBUG_METRICS: 0
      FLASK_ENV: development
      DD_TRACE_ENABLED: "false"
    env_file: docker.env
    ports:
      - '5000:5000'
    volumes:
    - ./:/usr/src/{{cookiecutter.directory_name}}/:cached
    - ./tests:/usr/src/{{cookiecutter.directory_name}}/tests/:cached
    healthcheck:
      test: curl --fail -s http://localhost:5000/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
