name: Docker to AWS ECR

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  IMAGE_NAME: {{cookiecutter.docker_image_name}}
  REPOSITORY_URL: 856965016623.dkr.ecr.us-east-1.amazonaws.com

jobs:
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: [self-hosted, main]

    steps:
      - uses: actions/checkout@v2

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          TAG: {% raw %}${{ steps.previoustag.outputs.tag }}{% endraw %}
        run: |
          docker build \
            -t $REPOSITORY_URL/$IMAGE_NAME:$TAG \
            -t $REPOSITORY_URL/$IMAGE_NAME:latest \
            -f Dockerfile .
          docker push -a $REPOSITORY_URL/$IMAGE_NAME
