name: Deploy to DockerHub

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  IMAGE_NAME: {{cookiecutter.docker_image_name}}
  REPOSITORY_URL: 856965016623.dkr.ecr.us-east-1.amazonaws.com

jobs:
  push:
    runs-on: main

    steps:
      - uses: actions/checkout@v5

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
        with:
            platforms: linux/amd64,linux/arm64

      - name: Create builder
        run: |
          docker buildx create --use

      - name: Inspect builder
        run: |
          docker buildx inspect --bootstrap

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_BUILDKIT: 1
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $REPOSITORY_URL/$IMAGE_NAME:$IMAGE_TAG \
            --push \
            -f Dockerfile .
