
bwell:
  environment: "client-sandbox-ue1"
  iamRole: arn:aws:iam::435975920517:role/client-sandbox-irsa-complaint-parser
  ingress:
    internal:
      enabled: true
      hosts:
        - host: {{cookiecutter.docker_image_name}}.client-sandbox.bwell.zone
          paths:
            - "/"
        - host: {{cookiecutter.docker_image_name}}.client-sandbox-ue1.bwell.zone
          paths:
            - "/"
    external:
      enabled: false

  env:
