
bwell:
  environment: "staging-ue1"
  iamRole: arn:aws:iam::435975920517:role/staging-irsa-complaint-parser
  ingress:
    internal:
      enabled: true
      hosts:
        - host: {{cookiecutter.docker_image_name}}.staging.bwell.zone
          paths:
            - "/"
        - host: {{cookiecutter.docker_image_name}}.staging-ue1.bwell.zone
          paths:
            - "/"
    external:
      enabled: falseÏ

  env:
